development:
  adapter: postgresql
  encoding: unicode
  database: convos
  pool: 5
  username: 
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: convos_test
  pool: 5
  username: 
  password: 